dist: trusty
sudo: required

language: java

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test jacoco:report coveralls:report

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install openjdk-8-jdk-headless -y
